services:
  ngrok:
    image: ngrok/ngrok:latest
    command: http --url=${NGROK_DOMAIN} grafana:3000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  grafana:
    image: grafana/grafana:main
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=provisioning,kubernetesDashboards
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_SERVER_ROOT_URL=https://${NGROK_DOMAIN}

    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - renderer
      - ngrok
    restart: unless-stopped
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

volumes:
  grafana-data:
